// Generated by CoffeeScript 1.7.1
(function() {
  var file, fs, processFile;

  fs = require('fs');

  file = __dirname + '/test.json';

  processFile = function(file, outFileName) {
    return fs.readFile(file, 'utf8', function(err, data) {
      var i, index, jsonString, node, nodes, _i, _j, _len;
      if (err) {
        console.log('Error: ' + err);
        return;
      }
      nodes = JSON.parse(data);
      for (index = _i = 0, _len = nodes.length; _i < _len; index = ++_i) {
        node = nodes[index];
        node._id = index;
        node.siblings = [];
        for (i = _j = 1; _j <= 9; i = ++_j) {
          if (node._id + i < nodes.length) {
            node.siblings.push(node._id + i);
          }
        }
      }
      jsonString = JSON.stringify(nodes, null, 4);
      return fs.writeFile(outFileName, jsonString, function(err) {
        if (err) {
          return console.log(err);
        } else {
          return console.log("The file was saved!");
        }
      });
    });
  };

  processFile(file, "out.json");

}).call(this);
